name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2

      - name: Build and analyze
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=my-server-app-jakub -Dsonar.organization=twoja-organizacja -Dsonar.token=\${{ secrets.SONAR_TOKEN }}
